# main.tfvars variables
variable "vpc" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_route_table_id" {}
variable "tags" {}
variable "env" {}
variable "alb" {}
variable "docdb" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}
variable "zone_id" {}
variable "shh_ingress_cidr" {}
variable "apps" {}
